---
 - name: Install dashboard on master node
   yum:
     name: cockpit-dashboard
     state: latest
     
 - name: add nodes to cockpit-dashboard on master
   template:
     src: templates/cockpit-machine.json.j2
     dest: /etc/cockpit/machines.d/{{ hostvars[item]['ansible_hostname'] }}.json
     owner: root
     group: root
     mode: 0644 
   with_items: "{{ groups.nodes }}"

 - name: add node keys to master known_hosts
   lineinfile:
     dest: /var/lib/cockpit/known_hosts 
     create: yes
     state: present
     line: "{{ lookup('pipe', 'ssh-keyscan -t ed25519 ' + hostvars[item]['ansible_facts']['enp0s8']['ipv4']['address']) }}"
   with_items: "{{ groups.nodes }}"
     
 - name: Start firewall
   service:
     name: firewalld
     state: started
     enabled: true

 - name: Configure firewall
   firewalld:
     port: "{{ item }}"
     permanent: true
     immediate: true
     state: enabled 
   with_items:
     - 9090/tcp

 - name: Start cockpit
   service:
     name: cockpit
     state: started

      
