---
- name: Install packages needed for all nodes 
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - cockpit
    - cockpit-bridge
    - cockpit-packagekit
    - cockpit-ws
    - cockpit-composer
    - cockpit-pcp
    - subscription-manager-cockpit
    - cockpit-system
    - cockpit-storaged
  tags:
  - packages

- name: Config Cockpit motd
  copy:
    content: "Web console: https://{{ hostvars['master']['ansible_facts']['enp0s8']['ipv4']['address'] }}:9090/@{{ ansible_facts['enp0s8']['ipv4']['address'] }}\n"
    dest: /etc/motd.d/cockpit